### ISSUE TITLE
Issue with vue 2.1.6

### ISSUE THREAD

**Issue by Phanu282003** [weifeiyue/vue-datepicker#11]
Hi 

Currently I am try to implement this control with vue/2.1.6 but It's has the error message as followed

'Cannot read property 'popup' of undefined
    at o.show (vue.datepicker.js:156)
    at Pi.run (vue.min.js:7)
    at B (vue.min.js:6)
    at Array.<anonymous> (vue.min.js:7)
    at e (vue.min.js:7)'

so how can I fixed the issue.

Thanks,
Phanu282003

**Comment by jjljyn** [comment]
@Phanu282003 
Hey man! I have the same issue.Did you fix this?

**Comment by Phanu282003** [comment]
Not yet. At the moment I am searching for new tool

**Comment by jjljyn** [comment]
@Phanu282003 Okey, I'm still using version 2.1.4. And what kind of new tool you are using?

**Comment by MaksimSkomorokh** [comment]
in ver. 2.1.8  I have the same issue.

**Comment by Paolocargnin** [comment]
For everyone who came here:
I fixed, you can look at the merge request here : 
https://github.com/weifeiyue/vue-datepicker/compare/master...Paolocargnin:patch-1

**Comment by weifeiyue** [comment]
@Phanu282003 @jjljyn @MaksimSkomorokh @Paolocargnin 
https://github.com/weifeiyue/vue-datepicker-local

**Comment by jjljyn** [comment]
nice👍
