### ISSUE TITLE
最好是点击确定之后才改变时间

### ISSUE THREAD

**Issue by Yusoo** [weifeiyue/vue-datepicker#3]
现在确定按钮只是单纯的隐藏选择器，要想根据日期变动做对应处理就只能watch传入的日期。
但目前这样只是点击日期不点确定都是会触发watch，特别是选择日期范围的时候，还会触发两次。

**Comment by weifeiyue** [comment]
@Yusoo 好的，迟点会改成这样子，谢谢您的建议

**Comment by weifeiyue** [comment]
@Yusoo 在0.1.2版本中，已经增加属性进行配置，看更新记录

**Comment by Yusoo** [comment]
@weifeiyue 看到了
