### ISSUE TITLE
[Suggestion] Date + Time

### ISSUE THREAD

**Issue by jpmurray** [weifeiyue/vue-datepicker#4]
Hello,

Is there any way you could also add the option of having a time picker?

**Comment by weifeiyue** [comment]
@jpmurray Thank you for your suggestion , i will do it later

**Comment by jizusun** [comment]
I beg the same feature :grin:

**Comment by nacr** [comment]
@weifeiyue any news?

**Comment by weifeiyue** [comment]
@jpmurray @smilingsun @nacr 
https://github.com/weifeiyue/vue-datepicker-local
