### ISSUE TITLE
start date and end date issue

### ISSUE THREAD

**Issue by bubnenkoff** [weifeiyue/vue-datepicker#6]
Could you help me in this topic http://stackoverflow.com/questions/38992894/why-syncing-data-do-not-work

@weifeiyue

**Comment by weifeiyue** [comment]
@bubnenkoff  :startdate is wrong, it should be :start-time

**Comment by bubnenkoff** [comment]
Thanks! Can i specify time in format:
startdate: '2011-11-11' ?
I mean in `data` section of Vue

**Comment by weifeiyue** [comment]
@bubnenkoff  sure
