### ISSUE TITLE
error when using formats as dd/MM/yyyy

### ISSUE THREAD

**Issue by pomarc** [weifeiyue/vue-datepicker#9]
If you use a date format like "dd/MM/yyyy" the month and day are switched (like if it was MM/dd/yyyy), so the resulting date after a click is wrong or NaN/NaN/NaN if you choose a day >12

MM/dd/yyyy works well, but almost all Europe uses dd/MM/yyyyy

**Comment by yajam** [comment]
Same issue

**Comment by weifeiyue** [comment]
@pomarc @yajam 
https://github.com/weifeiyue/vue-datepicker-local
